
version: 2

models:
  - name: venues
    description: "Venues table"
    columns:
      - name: venue_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      
      - name: venue_name
        data_tests: [not_null]
      
      - name: country
        data_tests: [not_null]
      
      - name: last_update
        data_tests: [not_null]

  - name: teams
    description: "Teams table"
    columns:
      - name: team_id
        data_tests:
          - unique
          - not_null

      - name: team
        data_tests: [not_null]

      - name: format
        data_tests: [not_null]

      - name: last_update
        data_tests: [not_null]

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - team
              - format

  - name: players
    columns:
      - name: player_id
        data_tests:
          - not_null

      - name: player_name
        data_tests: [not_null]

      - name: team_id
        data_tests:
          - relationships:
              arguments:
                to: ref('teams')
                field: 'team_id'
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - team_id
              - player_id

  - name: matches
    columns:
      - name: match_id
        data_tests:
          - unique

      - name: venue_id
        tests:
          - relationships:
              arguments:
                to: ref('venues')
                field: 'venue_id'

      - name: start_date
        data_tests: [not_null]

      - name: outcome_type
        data_tests: [not_null]


  - name: match_teams
    columns:
      - name: match_team_id
        data_tests:
          - unique
          - not_null

      - name: match_id
        tests:
          - relationships:
              arguments:
                to: ref('matches')
                field: 'match_id'

      - name: format
        data_tests: [not_null]

      - name: team
        data_tests: [not_null]
      
      - name: opponent
        data_tests: [not_null]
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - match_id
              - team


  - name: deliveries
    columns:
      - name: match_id
        data_tests:
          - relationships:
              arguments:
                to: ref('matches')
                field: 'match_id'

      - name: innings_number
        data_tests: [not_null]

      - name: over_number
        data_tests: [not_null]

      - name: ball_in_over
        data_tests: [not_null]
      
      - name: batter
        data_tests: [not_null]

      - name: bowler
        data_tests: [not_null]
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - match_id
              - innings_number
              - over_number
              - ball_in_over

  - name: innings
    columns:
      - name: match_id
        data_tests:
          - relationships:
              arguments:
                to: ref('matches')
                field: 'match_id'

      - name: innings_number
        data_tests: [not_null]

      - name: team
        data_tests: [not_null]

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - match_id
              - innings_number
